# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_sudoer_passwords:
  admin: $6$rounds=100000$JUkj1d3hCa6uFp6R$3rZ8jImyCpTP40e4I5APx7SbBvDCM8fB6GP/IGOrsk/GEUTUhl1i/Q2JNOpj9ashLpkgaCxqMqbFKdZdmAh26/

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  jackalope.io:
    env:
      db_password: jackalope_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "rY.hD3hFr^[@w/Y,5u#sZAEBzkCD3Ry0U1$pC>oEy:CMvhWej.ZdfSg[bK<,G=9e"
      secure_auth_key: "(cT0@I<yF(hDI,YznJ$eE[kZ%AKBq=>mPZw85c,^>#xmMWY{TuG+^4nQz_rBg2{O"
      logged_in_key: "-i|IVF.=JteL@@/Nqo}5qdjp%vxUt,O<3djH(2?vsuKGgi=E>p4qPjL3k)g}s&Ww"
      nonce_key: "c.s]GmkLY3=8mx`XgA?mg9EQt*-l6&EK)@BNlG,Df[mEjE$mOL+%k2Tm6!+C[@Qu"
      auth_salt: "meUKxha0Q{V8u0<>81sOGuDGHW:%]-]b4r[r&3n(@v_-Gq.b2d]?fp(7k47&,nb/"
      secure_auth_salt: "(rlw|nA9vKiBs29Q]S;m}vEzFZM*3Bhg!7D*IlW)(*P&G]7G=.%jkbQe^3GZ`!r{"
      logged_in_salt: "fIj^_tswP=rb0mi:h,#3V*aa9v^Ero2@t,)[Hq$6L#bt1Nsl$0U3a}%o2kfTGdEi"
      nonce_salt: "+wFGKDYN#CO<xiyA#t4uTZcFW.HAl/dfK-v8ftnUhS|u6U05?}m*V[Jv{{,dUHc;"
