# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_sudoer_passwords:
  admin: $6$rounds=100000$JUkj1d3hCa6uFp6R$3rZ8jImyCpTP40e4I5APx7SbBvDCM8fB6GP/IGOrsk/GEUTUhl1i/Q2JNOpj9ashLpkgaCxqMqbFKdZdmAh26/

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  jackalope.io:
    env:
      db_password: jackalope_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "sh/i_-]U0L@,e6;RNb(AR-p;Q@K@JL-8l>4q713?HQXidi(WjH00<OZH.Q!<`2s!"
      secure_auth_key: "en?=0I$v}[[YyGQR0;6V9KYO6KevlQ,<*rDFl4.|8i2idM$G(1921_]nd3{nYlB."
      logged_in_key: "].iFSZ1dab(&}}01Rvt.tcWuS/Rr1kE48``[TX5=>M-^H9/C(&bv:OWrrKalkkV5"
      nonce_key: "8rT!9}QM957EsE9}(%D3C,sSIpm&EU|n{Z/bp@_yKSL,?x$%^oaqetss@%(WK_Ya"
      auth_salt: "<B8<CC-fU+JufT/Jk=7y/?@J.$zVvyH0xm>6p(QuY_9P$Z3K@b,CflbMNKl!|FXq"
      secure_auth_salt: "P/4iEwlUOj6Kxo/}zexhQF$IDEeocaP2CpRQ0H6eVcZH78]V+|9Z%_Ufz=:8(L({"
      logged_in_salt: "qEY!Sby;x9}7Owt/#uG@1k71s;z|DO/oZ[@@|!zlcx)ze0!=`o(K6g-a6La$uX}}"
      nonce_salt: "I{<>D7.Cayp+tTf^{e;xcp+]?o{i:upiQ:-gmLJbtZJKV)?XoWcy>E}(U[>2BLD/"
