# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_sudoer_passwords:
  admin: $6$rounds=100000$JUkj1d3hCa6uFp6R$3rZ8jImyCpTP40e4I5APx7SbBvDCM8fB6GP/IGOrsk/GEUTUhl1i/Q2JNOpj9ashLpkgaCxqMqbFKdZdmAh26/

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  jackalope.io:
    env:
      db_password: jackalope_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "FiR`vfn5Ul{l1klbZIE!EkOZGvD7j?Z-:DI*v&&XO!G1}j]e4#P(-ekm{==:J7O*"
      secure_auth_key: "L0h<K{F=2|]+kl@Xm{U&E8>Vn]dhU[C}xf)&`h5,S|j:tRc&Kq*;eG-1e]u)5N_c"
      logged_in_key: "966Zi%FOsNG&DWV@wCcO5JB?>(42+;_XCv(#};[15?t18(k[J{wSv]ggqpbd}35^"
      nonce_key: "Sbr+$ZW=aYy-kk_o9b--L,s</iZN]GQ=ol0;-O=^|_Hv-8`uB{7>4*`%aBqDeG>{"
      auth_salt: "hNV^)Q{_@r,f69areX}o(-8xbm_!G*x:eK,YG9}5d@U;IBVT@pf?wE8&q]#<5ZgE"
      secure_auth_salt: "m6Yj7QgbfX!^CDKR/10|3FjQG/EpntSP}>3Qt=oiZOb{nfHD30e)DH#:2&3q}X|_"
      logged_in_salt: "M:3Q3rDk/IW@}BkT$kC+bo&<bRC;G#GrNuH8,3wcvx.nIp>z_ZZVA4q.ffm_C*O9"
      nonce_salt: "/|,*ehgi7ikl&[K5IH3@1wpWN]xM!IA3m0#O)0HiE!e9#yN^WC96WdQ1>nkq`cTT"
